language: python
python:
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran
# Install miniconda to avoid compiling scipy
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
# We support scipy 0.7.2, but it is not available on conda.
# So we test with 0.11. Our internal buildbot have 0.7.2.
  - conda create --yes -q -n py26 python=2.6 numpy=1.6 scipy=0.11 nose=1.1 pip 
  - source activate py26
  - pip install pydot
  - pip install theano
  - pip install . --no-deps --use-mirrors

script:
  - export THEANO_FLAGS=blas.ldflags="-lblas -lgfortran",warn.ignore_bug_before=all,on_opt_error=raise,on_shape_error=raise
  - python --version
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - echo "$PART"


#after_script:
after_failure:
  - cat /home/travis/.pip/pip.log
#after_success:
